#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

components-$(CONFIG_APP_HELLO_TIMER_CLIENT) += hello-timer-client
hello-timer-client: common libsel4 libmuslc libsel4muslcsys libutils
