#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_HELLO_TIMER) += hello-timer

# list of libraries the app needs to build
hello-timer-y = common libsel4 libmuslc \
            libsel4muslcsys \
            libsel4simple libsel4vka libsel4allocman libsel4vspace \
	    libsel4platsupport libplatsupport \
            libsel4utils \
            libcpio libelf \
            libutils

# set up correct simple lib for our kernel
ifdef CONFIG_KERNEL_STABLE
hello-timer-$(CONFIG_LIB_SEL4_SIMPLE_STABLE) += libsel4simple-stable
else
hello-timer-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default
endif

# add the companion app as a component so that we can elf load it
hello-timer-components-y += hello-timer-client
hello-timer-components = $(addprefix $(STAGE_BASE)/bin/, $(hello-timer-components-y))

hello-timer: export COMPONENTS=${hello-timer-components}
hello-timer: ${hello-timer-components-y} kernel_elf $(hello-timer-y)
