#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_HELLO_2) += hello-2

# list of libraries the app needs to build
hello-2-y = common libsel4 libmuslc \
            libsel4muslcsys \
            libsel4simple libsel4vka libsel4allocman \
            libsel4platsupport \
            libutils libsel4simple-default libsel4debug

hello-2: kernel_elf $(hello-2-y)
