#!/bin/bash
#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

# Auto-generates the kernel_symbols table for accessing kernel symbols.

if [ $# -ne 2 ]; then
    echo "Usage: $0 objdump-command kernel.elf" 1>&2
    exit 1
fi

cat - <<EOT
/* Auto-generated by $0. Do not edit manually. */

/* Include Kconfig variables. */
#include <autoconf.h>

#include <string.h>

static struct kernel_symbol {
    char *symbol;
    void *addr;
} kernel_symbols[] = {
EOT

# Objdump the symbol table and format it nicely for C.
"$1" --syms "$2" \
    | grep --color=none "^[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f] " \
    | sed 's/\([0-9a-f]*\) .* \(.*\)/    { .symbol = "\2", .addr = (void*)0xf\1 },/g'

cat - <<EOT
    { .symbol = NULL, .addr = (void*)NULL }, /* Terminate array. */
};

void * resolve_kernel_symbol(char *symbol) {
    for (int i = 0; kernel_symbols[i].symbol != NULL ; ++i) {
        if (!strcmp(kernel_symbols[i].symbol, symbol)) {
            return kernel_symbols[i].addr;
        }
    }
    return NULL;
}
EOT
