#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

apps-$(CONFIG_APP_HELLO_1) += hello-1

# list of libraries the app needs to build
hello-1-y = common libsel4 libmuslc \
            libsel4muslcsys \
            libsel4platsupport \
            libutils libsel4utils libsel4debug

hello-1: kernel_elf $(hello-1-y)
