#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

components-$(CONFIG_APP_HELLO_4_APP) += hello-4-app
hello-4-app: common libsel4 libmuslc libsel4muslcsys libutils libsel4utils libsel4debug libsel4platsupport libplatsupport
