#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

components-$(CONFIG_APP_HELLO_LIBS_4_APPS)        += hello-libs-4-apps
hello-libs-4-apps: common libsel4 libmuslc libsel4muslcsys libplatsupport libutils

# hello-libs-4-apps: common libsel4 libmuslc libcpio libsel4utils libsel4muslcsys libsel4allocman libsel4test libelf libplatsupport libsel4platsupport libsel4vspace
