#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_HELLO_4) += hello-4

# list of libraries the app needs to build
hello-4-y = common libsel4 libmuslc libsel4muslcsys \
            libsel4simple libsel4vka libsel4allocman libsel4vspace \
	    libplatsupport libsel4platsupport \
            libsel4utils \
            libcpio libelf

# set up correct simple lib for our kernel
ifdef CONFIG_KERNEL_STABLE
hello-4-$(CONFIG_LIB_SEL4_SIMPLE_STABLE) += libsel4simple-stable
else
hello-4-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default
endif

# add the companion app  as a component so that we can elf load it
hello-4-components-y += hello-4-app
hello-4-components = $(addprefix $(STAGE_BASE)/bin/, $(hello-4-components-y))

hello-4: export COMPONENTS=${hello-4-components}
hello-4: ${hello-4-components-y} kernel_elf $(hello-4-y)
