#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

apps-$(CONFIG_APP_HELLO_TIMER) += hello-timer

# list of libraries the app needs to build
hello-timer-y = common libsel4 libmuslc \
            libsel4muslcsys \
            libsel4simple libsel4vka libsel4allocman libsel4vspace \
            libsel4platsupport libplatsupport \
            libsel4utils \
            libcpio libelf \
            libutils libsel4simple-default libsel4debug

# add the companion app as a component so that we can elf load it
hello-timer-components-y += hello-timer-client
hello-timer-components = $(addprefix $(STAGE_BASE)/bin/, $(hello-timer-components-y))

hello-timer: export COMPONENTS=${hello-timer-components}
hello-timer: ${hello-timer-components-y} kernel_elf $(hello-timer-y)
