#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_HELLO_CAMKES_0) += hello-camkes-0
hello-camkes-0: libsel4 libmuslc libsel4muslccamkes libsel4camkes libsel4platsupport libsel4sync libsel4debug libsel4bench
