#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_HELLO_3_NOLIBS) += hello-3-nolibs

# list of libraries the app needs to build
hello-3-nolibs-y = common libsel4 libmuslc \
            libsel4muslcsys \
            libsel4simple libsel4vka libsel4allocman libsel4vspace \
            libsel4platsupport

# set up correct simple lib for our kernel
ifdef CONFIG_KERNEL_STABLE
hello-3-nolibs-$(CONFIG_LIB_SEL4_SIMPLE_STABLE) += libsel4simple-stable
else
hello-3-nolibs-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default
endif

hello-3-nolibs: kernel_elf $(hello-3-nolibs-y)

