# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: Test

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'LICENSES/**'
      - '.*'

  # allow manual trigger
  workflow_dispatch:

  # allow explicit trigger from other repos when dependencies have changed
  repository_dispatch:
    types: [deps-update]

jobs:
  code:
    name: Freeze Code
    runs-on: ubuntu-latest
    outputs:
      xml: ${{ steps.repo.outputs.xml }}
    steps:
    - id: repo
      uses: seL4/ci-actions/repo-checkout@master
      with:
        manifest_repo: sel4-tutorials-manifest
        manifest: master.xml

  test:
    name: Tutorial Solution
    needs: code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
        - capabilities
        - dynamic-1
        - dynamic-2
        - dynamic-3
        - dynamic-4
        - hello-camkes-0
        - hello-camkes-1
        - hello-camkes-2
        - hello-camkes-timer
        - hello-world
        - interrupts
        - ipc
        - mapping
        - notifications
        - untyped
        - threads
        - fault-handlers
        - mcs
    steps:
    - uses: seL4/ci-actions/tutorials@master
      with:
        app: ${{ matrix.app }}
        xml: ${{ needs.code.outputs.xml }}

  deploy:
    name: Deploy manifest
    if: ${{ github.repository_owner == 'seL4' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [test, code]
    steps:
    - name: Deploy
      uses: seL4/ci-actions/manifest-deploy@master
      with:
        xml: ${{ needs.code.outputs.xml }}
        manifest_repo: sel4-tutorials-manifest
      env:
        GH_SSH: ${{ secrets.CI_SSH }}
